//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet_E_Commerce_Glasses_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Consumer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consumer()
        {
            this.Bills = new HashSet<Bill>();
            this.RateProducts = new HashSet<RateProduct>();
        }
    
        public int IdConsumer { get; set; }
        public Nullable<int> IdAccount { get; set; }
        public string Username { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string NumberPhone { get; set; }
        public string Image { get; set; }
        public string ListCart { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateProduct> RateProducts { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
            public string GetDateOfBirthAsString()
            {
                DateTime date = DateOfBirth ?? DateTime.Now.Date;
                return ((DateTime)date).ToString("yyyy-MM-dd");
            }

    }
}
