//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet_E_Commerce_Glasses_Web.Models
{
    using DotNet_E_Commerce_Glasses_Web.Utils;
    using System;
    using System.Collections.Generic;
    
    public partial class DetailBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailBill()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int IdDetailBill { get; set; }
        public string ListBill { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }

        public Dictionary<int, int> ListBills() => JsonUtils.ConvertStrToDic(this.ListBill);
        public void SetListBill(Dictionary<int, int> dicListProducts)
        {
            this.ListBill = JsonUtils.ConvertDicToJson(dicListProducts);
        }
    }
}
