//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet_E_Commerce_Glasses_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int IdManager { get; set; }
        public Nullable<int> IdAccount { get; set; }
        public string Username { get; set; }
        public string Position { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
