//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet_E_Commerce_Glasses_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateProduct
    {
        public int IdRate { get; set; }
        public Nullable<int> IdConsumer { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public string TitleRate { get; set; }
        public string ContentRate { get; set; }
        public Nullable<System.DateTime> DateOfRate { get; set; }
        public Nullable<int> RateStar { get; set; }
    
        public virtual Consumer Consumer { get; set; }
        public virtual Product Product { get; set; }
    }
}
